name: Sync upstream

on:
  schedule:
    - cron: '12 12 * * *' # 每小时自动运行一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/main --allow-unrelated-histories -m "Sync upstream"
          git push origin master
