name: Sync upstream

on:
  schedule:
    - cron: '12 12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories -m "Sync upstream" || true

      - name: Auto-resolve conflicts (prefer upstream)
        run: |
          git diff --name-only --diff-filter=U | while read filename; do
            git checkout --theirs "$filename"
            git add "$filename"
          done
          git diff --name-only --diff-filter=U | xargs -r rm
          git commit -m "Auto-resolve merge conflicts (prefer upstream)" || echo "No conflicts to commit"
          git push origin master
