name: Merge AI Model Rules For ClashVerge

on:
  push:
    paths:
      - rule/Clash/**
  workflow_dispatch:

jobs:
  merge-ai-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge yaml AI model rules (payload only, filtered by AI keywords)
        run: |
          mkdir -p merged
          AI_KEYWORDS="chatgpt|claude|gemini|llama|midjourney|stable-diffusion|copilot|mistral|groq|openai|anthropic"
          # 只查找 rule/Clash/*/*.yml 或 *.yaml 文件，合并 payload 下内容，过滤 AI 关键字、去注释和空行
          find rule/Clash/ -mindepth 2 -maxdepth 2 -type f \( -name "*.yml" -o -name "*.yaml" \) | \
          xargs awk '/^payload:/ {flag=1; next} /^ *- / && flag {print $0} /^$/ {flag=0}' | \
          grep -iE "$AI_KEYWORDS" | \
          sed '/^\s*#/d;/^\s*$/d' | \
          sort | uniq > merged/tmp_rules.txt
          # 生成最终合并的 yaml 文件，只保留一个 payload
          echo "payload:" > merged/ai_rules_clashverge.txt
          awk '{print "  " $0}' merged/tmp_rules.txt >> merged/ai_rules_clashverge.txt
          rm merged/tmp_rules.txt

      - name: Upload merged file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai_rules_clashverge
          path: merged/ai_rules_clashverge.txt

      - name: Commit merged rules
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add merged/ai_rules_clashverge.txt
          git commit -m "Auto-merge AI model rules for ClashVerge"
          git push

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Update rules"
            git push
          else
            echo "No changes to commit."
          fi
